apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: production
spec:
  kind: Permanent
  label: Production
  namespace: devtools-production
  order: 200
  previewGitInfo:
    user: {}
  promotionStrategy: Manual
  source:
    ref: master
    url: https://github.com/nuxeo-sandbox/environment-hissember-production.git
  teamSettings: {}
status: {}
