jenkins-x-platform:
  PipelineSecrets:
    DockerConfig: |-
      {
          "credHelpers": {
              "gcr.io": "gcloud",
              "us.gcr.io": "gcloud",
              "eu.gcr.io": "gcloud",
              "asia.gcr.io": "gcloud",
              "staging-k8s.gcr.io": "gcloud"
          }
      }
  jenkins:
    Agent:
      DockerHostPath: /var/run/dind/docker.sock
      PodTemplates:
        JX-base:
          DevPodPorts: 5005, 8080
    Master:
      Image: jenkins-x-docker-registry:5000/nuxeo/devtools/jenkinsx
      ImageTag: 0.0.1-5bbffc6-dirty
    Servers:
      Global:
        EnvVars:
          DOCKER_REGISTRY: jenkins-x-docker-registry
  postinstalljob:
    enabled: "true"
